version: '3.8'
services:
  postgres:
    image: postgres:15.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_spring_auth_server
    ports:
      - "5432:5432"
    volumes:
      - my-spring-auth-server:/my-spring-auth-server

volumes:
  my-spring-auth-server-volume: